env:
  global:
    - LC_CTYPE=en_US.UTF-8
    
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      language: generic
      env:
        - JOB=Linux
        - SWIFT_VERSION=5.1.3
      script:
        - swift --version
        - swift build
        - swift test
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

notifications:
  email: false
